apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: f1strategizer-2401076-ingress
  namespace: "2401076"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: f1strategizer.imcc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: f1strategizer-2401076
            port:
              number: 80
